spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notice
    username: root
    password: mariadb
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 9999
